imports:
    - { resource: "../grids/tavy315_sylius_labels_admin_label.yaml" }

sylius_grid:
    templates:
        action:
            tavy315_labels_default: "@Tavy315SyliusLabelsPlugin/Admin/Grid/Action/tavy315_labels_default.html.twig"
